### ISSUE TITLE
rxjs error

### ISSUE THREAD

**Issue by transtone** [antfu/vitesse-nuxt3#90] opened 2023-05-06 09:38 UTC
```cmd
[nuxt] [request error] [unhandled] [500] Cannot find module './internal/Observable'                                                                                                                                         17:34:59  
Require stack:
- D:\code\github\vitesse-nuxt3-main\rxjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Module._load (node:internal/modules/cjs/loader:920:27)
  at Module.require (node:internal/modules/cjs/loader:1141:19)
  at require (node:internal/modules/cjs/helpers:110:18)
  at D:\code\github\vitesse-nuxt3-main\rxjs:17:20
  at ViteNodeRunner.directRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:331:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:171:14)
  at async ViteNodeRunner.dependencyRequest (/D:/code/github/vitesse-nuxt3-main/node_modules/.pnpm/vite-node@0.30.1_@types+node@18.14.0/node_modules/vite-node/dist/client.mjs:220:14)
  at async D:\code\github\vitesse-nuxt3-main\node_modules\.pnpm\@vueuse+rxjs@10.1.2_rxjs@7.8.1_vue@3.2.47\node_modules\@vueuse\rxjs\index.mjs:1:31
```

when add rxjs to `app.vue` like this

```vue
<script setup lang="ts">
import { useObservable } from '@vueuse/rxjs'
import { interval } from 'rxjs'
import { mapTo, scan, startWith } from 'rxjs/operators'

import { appName } from '~/constants'

const count = useObservable(
  interval(1000).pipe(
    mapTo(1),
    startWith(0),
    scan((total, next) => next + total),
  ),
)

useHead({
  title: appName,
})
</script>

```

**Comment by antfu** [comment] 2023-05-06 13:33
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-06 13:33 UTC

**Comment by transtone** [comment] 2023-05-07 00:24
sorry, the minimal reproduction is : https://github.com/transtone/vitesse-nuxt3
