### ISSUE TITLE
strange behavior: visual errors in 'index.vue' but not in others.

### ISSUE THREAD

**Issue by matifanger** [antfu/vitesse-nuxt3#38] opened 2022-05-02 02:32 UTC
Exactly same code, both working nice, but visual errors in 'index' file.

index.vue
![Code_5UMoY6VOya](https://user-images.githubusercontent.com/39188240/166177748-2b688095-3b7f-4883-9758-1811a6c197ec.png)

query.vue
![Code_Wt9E50SASR](https://user-images.githubusercontent.com/39188240/166177751-7ba6c26c-e49c-41d3-a4dc-66b74ef6cb81.png)

**Comment by antfu** [comment] 2022-05-02 16:12
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-02 16:12 UTC

**Comment by matifanger** [comment] 2022-05-02 17:09
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

Done!

**Comment by matifanger** [comment] 2022-05-02 23:28
Restarted the VSCode, now it's solved.
